name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 配置 protoc环境
      uses: zchee/setup-protoc@v1.2.0
      with:
        version: 21.8
        
    - name: 配置 proto gen go环境
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      
    - name: 生成natsrpc协议
      run: make gen_natsrpc

    - name: 生成客户端协议
      run: make gen_proto

    - name: 生成二进制
      run: make build

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
